<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Spectro</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Commands\**" />
    <EmbeddedResource Remove="Commands\**" />
    <None Remove="Commands\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Realm" Version="20.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spectro.Core\Spectro.Core.csproj" />
  </ItemGroup>

</Project>