// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace NewsBlurSharp.Model.Response
{

    public class SocialProfile
    {
        [JsonProperty("website")]
        public string Website { get; set; }

        [JsonProperty("following_user_ids")]
        public string[] FollowingUserIds { get; set; }

        [JsonProperty("following_count")]
        public int FollowingCount { get; set; }

        [JsonProperty("shared_stories_count")]
        public int SharedStoriesCount { get; set; }

        [JsonProperty("private")]
        public object Private { get; set; }

        [JsonProperty("large_photo_url")]
        public string LargePhotoUrl { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("feed_address")]
        public string FeedAddress { get; set; }

        [JsonProperty("user_id")]
        public int UserId { get; set; }

        [JsonProperty("feed_link")]
        public string FeedLink { get; set; }

        [JsonProperty("follower_user_ids")]
        public object[] FollowerUserIds { get; set; }

        [JsonProperty("location")]
        public object Location { get; set; }

        [JsonProperty("popular_publishers")]
        public object PopularPublishers { get; set; }

        [JsonProperty("follower_count")]
        public int FollowerCount { get; set; }

        [JsonProperty("username")]
        public string Username { get; set; }

        [JsonProperty("bio")]
        public object Bio { get; set; }

        [JsonProperty("average_stories_per_month")]
        public int AverageStoriesPerMonth { get; set; }

        [JsonProperty("feed_title")]
        public string FeedTitle { get; set; }

        [JsonProperty("photo_service")]
        public object PhotoService { get; set; }

        [JsonProperty("stories_last_month")]
        public int StoriesLastMonth { get; set; }

        [JsonProperty("photo_url")]
        public string PhotoUrl { get; set; }

        [JsonProperty("num_subscribers")]
        public int NumSubscribers { get; set; }

        [JsonProperty("protected")]
        public object Protected { get; set; }
    }

    public class Preferences
    {

        [JsonProperty("intro_page")]
        public string IntroPage { get; set; }
    }

    public class UserProfile
    {

        [JsonProperty("hide_getting_started")]
        public bool HideGettingStarted { get; set; }

        [JsonProperty("preferences")]
        public Preferences Preferences { get; set; }

        [JsonProperty("tutorial_finished")]
        public bool TutorialFinished { get; set; }

        [JsonProperty("has_setup_feeds")]
        public bool HasSetupFeeds { get; set; }

        [JsonProperty("is_premium")]
        public bool IsPremium { get; set; }

        [JsonProperty("dashboard_date")]
        public string DashboardDate { get; set; }

        [JsonProperty("has_trained_intelligence")]
        public bool HasTrainedIntelligence { get; set; }

        [JsonProperty("has_found_friends")]
        public bool HasFoundFriends { get; set; }
    }

    public class StarredCount
    {

        [JsonProperty("count")]
        public int Count { get; set; }

        [JsonProperty("feed_address")]
        public string FeedAddress { get; set; }

        [JsonProperty("tag")]
        public object Tag { get; set; }

        [JsonProperty("feed_id")]
        public object FeedId { get; set; }
    }

    public class FeedItem
    {

        [JsonProperty("subs")]
        public int Subs { get; set; }

        [JsonProperty("favicon_url")]
        public string FaviconUrl { get; set; }

        [JsonProperty("is_push")]
        public bool IsPush { get; set; }

        [JsonProperty("feed_opens")]
        public int FeedOpens { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("s3_icon")]
        public bool S3Icon { get; set; }

        [JsonProperty("feed_link")]
        public string FeedLink { get; set; }

        [JsonProperty("updated_seconds_ago")]
        public int UpdatedSecondsAgo { get; set; }

        [JsonProperty("favicon_fetching")]
        public bool FaviconFetching { get; set; }

        [JsonProperty("ng")]
        public int Ng { get; set; }

        [JsonProperty("favicon_border")]
        public string FaviconBorder { get; set; }

        [JsonProperty("last_story_date")]
        public string LastStoryDate { get; set; }

        [JsonProperty("nt")]
        public int Nt { get; set; }

        [JsonProperty("not_yet_fetched")]
        public bool NotYetFetched { get; set; }

        [JsonProperty("updated")]
        public string Updated { get; set; }

        [JsonProperty("average_stories_per_month")]
        public int AverageStoriesPerMonth { get; set; }

        [JsonProperty("ps")]
        public int Ps { get; set; }

        [JsonProperty("feed_address")]
        public string FeedAddress { get; set; }

        [JsonProperty("feed_title")]
        public string FeedTitle { get; set; }

        [JsonProperty("favicon_fade")]
        public string FaviconFade { get; set; }

        [JsonProperty("is_newsletter")]
        public bool IsNewsletter { get; set; }

        [JsonProperty("last_story_seconds_ago")]
        public int LastStorySecondsAgo { get; set; }

        [JsonProperty("favicon_color")]
        public string FaviconColor { get; set; }

        [JsonProperty("stories_last_month")]
        public int StoriesLastMonth { get; set; }

        [JsonProperty("active")]
        public bool Active { get; set; }

        [JsonProperty("fetched_once")]
        public bool FetchedOnce { get; set; }

        [JsonProperty("favicon_text_color")]
        public string FaviconTextColor { get; set; }

        [JsonProperty("subscribed")]
        public bool Subscribed { get; set; }

        [JsonProperty("num_subscribers")]
        public int NumSubscribers { get; set; }

        [JsonProperty("s3_page")]
        public bool S3Page { get; set; }

        [JsonProperty("min_to_decay")]
        public int MinToDecay { get; set; }

        [JsonProperty("search_indexed")]
        public bool SearchIndexed { get; set; }
    }

    public class Feeds
    {
        [JsonProperty("19354")]
        public FeedItem Feed { get; set; }
    }

    public class Facebook
    {

        [JsonProperty("syncing")]
        public bool Syncing { get; set; }

        [JsonProperty("facebook_picture_url")]
        public object FacebookPictureUrl { get; set; }

        [JsonProperty("facebook_uid")]
        public object FacebookUid { get; set; }
    }

    public class Twitter
    {

        [JsonProperty("twitter_username")]
        public object TwitterUsername { get; set; }

        [JsonProperty("syncing")]
        public bool Syncing { get; set; }

        [JsonProperty("twitter_picture_url")]
        public object TwitterPictureUrl { get; set; }

        [JsonProperty("twitter_uid")]
        public object TwitterUid { get; set; }
    }

    public class Gravatar
    {

        [JsonProperty("gravatar_picture_url")]
        public string GravatarPictureUrl { get; set; }
    }

    public class Appdotnet
    {

        [JsonProperty("syncing")]
        public bool Syncing { get; set; }

        [JsonProperty("appdotnet_uid")]
        public object AppdotnetUid { get; set; }

        [JsonProperty("appdotnet_picture_url")]
        public object AppdotnetPictureUrl { get; set; }
    }

    public class Upload
    {

        [JsonProperty("upload_picture_url")]
        public object UploadPictureUrl { get; set; }
    }

    public class SocialServices
    {

        [JsonProperty("facebook")]
        public Facebook Facebook { get; set; }

        [JsonProperty("twitter")]
        public Twitter Twitter { get; set; }

        [JsonProperty("gravatar")]
        public Gravatar Gravatar { get; set; }

        [JsonProperty("appdotnet")]
        public Appdotnet Appdotnet { get; set; }

        [JsonProperty("upload")]
        public Upload Upload { get; set; }
    }

    public class FeedResponse
    {

        [JsonProperty("folders")]
        public int[] Folders { get; set; }

        [JsonProperty("saved_searches")]
        public object[] SavedSearches { get; set; }

        [JsonProperty("user_id")]
        public int UserId { get; set; }

        [JsonProperty("social_profile")]
        public SocialProfile SocialProfile { get; set; }

        [JsonProperty("user_profile")]
        public UserProfile UserProfile { get; set; }

        [JsonProperty("starred_counts")]
        public StarredCount[] StarredCounts { get; set; }

        [JsonProperty("starred_count")]
        public int StarredCount { get; set; }

        [JsonProperty("is_staff")]
        public bool IsStaff { get; set; }

        [JsonProperty("result")]
        public string Result { get; set; }

        [JsonProperty("authenticated")]
        public bool Authenticated { get; set; }

        [JsonProperty("feeds")]
        public Feeds Feeds { get; set; }

        [JsonProperty("social_services")]
        public SocialServices SocialServices { get; set; }

        [JsonProperty("categories")]
        public object Categories { get; set; }

        [JsonProperty("social_feeds")]
        public object[] SocialFeeds { get; set; }
    }

}
