<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>AppContainerExe</OutputType>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <RootNamespace>Spectro</RootNamespace>
    <AssemblyName>Spectro</AssemblyName>
    <DefaultLanguage>en-US</DefaultLanguage>
    <ApplicationManifest>Package.appxmanifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <UseUwp>true</UseUwp>
    <UseUwpTools>true</UseUwpTools>
    <WindowsSdkPackageVersion>10.0.26100.1</WindowsSdkPackageVersion>
    <AssetTargetFallback>uap10.0</AssetTargetFallback>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cimbalino.Toolkit" Version="2.5.2" />
    <PackageReference Include="Cimbalino.Toolkit.Controls" Version="2.5.2" />
    <PackageReference Include="Cimbalino.Toolkit.Core" Version="2.5.2" />
    <PackageReference Include="Microsoft.Toolkit.Uwp" Version="2.0.0" />
    <PackageReference Include="Microsoft.Toolkit.Uwp.Connectivity" Version="2.0.0" />
    <PackageReference Include="Microsoft.Toolkit.Uwp.UI" Version="2.0.0" />
    <PackageReference Include="Microsoft.Toolkit.Uwp.UI.Animations" Version="2.0.0" />
    <PackageReference Include="Microsoft.Toolkit.Uwp.UI.Controls" Version="2.0.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Uwp.Managed" Version="2.0.0" />
    <PackageReference Include="MvvmLightLibsStd10" Version="5.4.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NewsBlurSharp\NewsBlurSharp.csproj" />
    <ProjectReference Include="..\Spectro.Core\Spectro.Core.csproj" />
    <ProjectReference Include="..\Spectro.ViewModels\Spectro.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PRIResource Include="Strings\en-us\Resources.resw" />
  </ItemGroup>
</Project>
