<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NewsBlurSharp\NewsBlurSharp.csproj" />
    <ProjectReference Include="..\Spectro.Domain\Spectro.Domain.csproj" />
  </ItemGroup>

</Project>
